version: "3.5"
services:
  centos7geoipphp71:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: 7.8.2003
        image: php-7.1
  centos7geoipphp71rel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.rel
      args:
        centos: 7.8.2003
        image: php7-7.1
  centos8geoipphp71:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: 8.2.2004
        image: php-7.1
  centos8geoipphp71rel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.rel
      args:
        centos: 8.2.2004
        image: php7-7.1

volumes:
  rpms:
    name: rpms
  rpm8:
    name: rpm8
  rpm7:
    name: rpm7
