version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.1

workflows:
  geoipbuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7geoip
          build_service: centos7geoip
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8geoip
          build_service: centos8geoip
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7geoipphp73
          build_file: docker-compose.php73.yml
          build_service: centos7geoipphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8geoipphp73
          build_file: docker-compose.php73.yml
          build_service: centos8geoipphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7geoipphp80
          build_file: docker-compose.php80.yml
          build_service: centos7geoipphp80
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8geoipphp80
          build_file: docker-compose.php80.yml
          build_service: centos8geoipphp80
          bintray_uploader: centos8bintray